favicon: null
name: existing in thought
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.09677419
  brandStrength: 0.4516129
  lightness: 0.8996416
  brandColors:
    - '#170B0E'
    - '#D8BE9A'
    - '#FCD0BD'
    - '#4B3018'
    - '#A30B2F'
  rhythmicContrast: 0.1326165
typography_spectrum: 0.5340502
layout_spectrum: 0.9050179
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
