name: existing in thought
favicon: null
layout_spectrum: 0.26382
typography_spectrum: 0
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#170B0E'
    - '#D8BE9A'
    - '#FCD0BD'
    - '#4B3018'
    - '#A30B2F'
  brandStrength: 0.4516129
  lightness: 0.8996416
  saturation: 0.5
  rhythmicContrast: 0.1326165
purpose: []
